import "./globals.css";
import type { Metadata } from "next";
import { ScrollProvider } from "../components/layout/ScrollProvider";
import FloatingWhatsApp from "../components/clinic/FloatingWhatsApp";
import { JetBrains_Mono, Oswald, Sora } from "next/font/google";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en"
      className={`${sora.variable} ${oswald.variable} ${jetbrainsMono.variable} antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <ScrollProvider>
          {children}
          <FloatingWhatsApp />
        </ScrollProvider>
      </body>
    </html>
  );
}
